License show
curationexperts/cypripedium pull request #539
Opened 2022-10-27 15:32 UTC by MPLSFedResearchTZ

This is to change the display of license text of collections to be clickable hyperlink.

2022-11-08 19:40 UTC, mark-dce requested changes
Can you find a way to write the one spec without an if statement in it?  Either test only one case or write two separate tests, one for each branch of the conditional.

2022-11-08 19:40 UTC, mark-dce commented on spec/helpers/collection_license_attribute_renderer_helper_spec.rb
> +      if microdata_value_attributes(:license).present?
It's generally best practice not to have `if` statements in your specs.

Can you break this apart into two separate tests, one that tests for when the microdata is present and one that tests when it's not.   If the expectation is that the microdata should always be present or should always be absent, you only need one branch of the test.

2022-11-08 20:41 UTC, MPLSFedResearchTZ commented on spec/helpers/collection_license_attribute_renderer_helper_spec.rb
> +      if microdata_value_attributes(:license).present?
Will make the change. Thank you very much!

2022-11-10 17:44 UTC, mark-dce approved these changes
👍

2022-11-10 17:44 UTC, merged