Sort works: sort the work list in a collection page
curationexperts/cypripedium pull request #542
Opened 2022-12-05 03:32 UTC by MPLSFedResearchTZ

2022-12-05 17:13 UTC, mark-dce requested changes

2022-12-05 17:13 UTC, mark-dce commented on Gemfile
> +  gem 'ruby-debug-ide'
This gem, and possibly the others, should not be run in the production environment, please move the testing gems to the "development, testing" gem group lower in this file.

2022-12-05 17:20 UTC, MPLSFedResearchTZ commented
The rubyu-debug-ide gem is in the "development, testing" group as shown below:
![image](https://user-images.githubusercontent.com/93392603/205701379-e9597e4a-c991-4c97-b419-933f6aadfb47.png)

2022-12-06 19:36 UTC, MPLSFedResearchTZ commented on Gemfile
> +  gem 'ruby-debug-ide'
The rubyu-debug-ide gem is in the "development, testing" group as shown below:
![image](https://user-images.githubusercontent.com/93392603/206005808-f9f2e03f-22b1-49fe-80e0-42ee9e4c52a5.png)

2022-12-08 15:00 UTC, mark-dce commented on Gemfile
> +  gem 'ruby-debug-ide'
Tao - my apologies, I was misreading the file because of the way git was displaying the diff.  I'm sorry for the delay.

2022-12-08 15:00 UTC, mark-dce approved these changes

2022-12-08 15:00 UTC, merged